apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: katib-backend-config
spec:
  iap:
    enabled: true
    oauthclientCredentials:
      secretName: katib-iap
  healthCheck:
    checkIntervalSec: 15
    port: 8080
    requestPath: /katib/
    type: HTTP
  logging:
    enable: true
    sampleRate: 1.0
  timeoutSec: 60
